# Generated by Django 4.2.16 on 2025-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(db_index=True, unique=True, verbose_name='номер телефона'),
        ),
    ]
