# Generated by Django 4.2.16 on 2024-10-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.booking'),
        ),
    ]
