# Generated by Django 4.2.16 on 2024-11-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0029_alter_formforguardianship_user'),
        ('Booking', '0001_initial'),
        ('Users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='booked',
        ),
        migrations.AddField(
            model_name='user',
            name='guardianship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyGuardianship', to='Cats.formforguardianship', verbose_name='Опекунство'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Мяукоины'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='номер телефона'),
        ),
    ]
