# Generated by Django 4.2.16 on 2024-11-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='guardianship',
        ),
    ]
