# Generated by Django 4.2.16 on 2024-11-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_user_guardianship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(unique=True, verbose_name='номер телефона'),
        ),
    ]
