# Generated by Django 4.2.16 on 2024-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
