# Generated by Django 4.2.16 on 2024-11-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_user_password1_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
