# Generated by Django 4.2.16 on 2024-11-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_remove_user_password1_remove_user_password2'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
