# Generated by Django 4.2.16 on 2024-12-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_remove_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
