# Generated by Django 4.2.16 on 2024-12-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
