# Generated by Django 4.2.16 on 2025-02-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.CharField(verbose_name='Описание')),
                ('product_id', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': 'Продукт для подписки',
                'verbose_name_plural': 'Продукты для подписки',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='PriceStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('unit_amount', models.CharField(verbose_name='Сумма на опекунство')),
                ('interval', models.CharField(verbose_name='Интервал')),
                ('currency', models.CharField(default='usd', verbose_name='Валюта')),
                ('price_id', models.CharField(blank=True, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.productstripe', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Цена подписки',
                'verbose_name_plural': 'Цены подписок',
                'db_table': 'Price',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSessionStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_session_id', models.CharField(unique=True)),
                ('customer_id', models.CharField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('subscription_id', models.CharField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.pricestripe')),
            ],
            options={
                'verbose_name': 'Информация о сесссии',
                'verbose_name_plural': 'Информация о сесссиях',
                'db_table': 'CheckoutSessionStripe',
            },
        ),
    ]
