# Generated by Django 4.2.16 on 2025-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstripe',
            name='product_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
