# Generated by Django 4.2.16 on 2025-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Эл. почта'),
            preserve_default=False,
        ),
    ]
