# Generated by Django 4.2.16 on 2025-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(verbose_name='номер телефона'),
        ),
    ]
