# Generated by Django 4.2.16 on 2025-01-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(verbose_name='Город')),
                ('street', models.CharField(verbose_name='Улица')),
                ('house_number', models.CharField(verbose_name='Номер строения')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='InfAboutCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(unique=True, verbose_name='Номер телефона')),
                ('working_hours', models.CharField(verbose_name='Часы работы')),
                ('count_of_cats', models.PositiveIntegerField(verbose_name='Количество котов')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Стоимость посещения')),
                ('duration_of_the_visit', models.PositiveSmallIntegerField(verbose_name='Продолжительность посещения')),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.address', verbose_name='Адрес кафе')),
            ],
            options={
                'verbose_name': 'Информаци о кафе',
                'verbose_name_plural': 'Информацию о кафе',
                'db_table': 'Information',
            },
        ),
    ]
