# Generated by Django 4.2.16 on 2024-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_infaboutcafemodel_infaboutcafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infaboutcafe',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Стоимость посещения'),
        ),
    ]
