# Generated by Django 4.2.16 on 2025-03-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Мяукоин',
                'verbose_name_plural': 'Мяукоины',
                'db_table': 'Bonuses',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(verbose_name='Процент скидки')),
                ('description', models.CharField(verbose_name='Описание')),
                ('code', models.CharField(max_length=15, verbose_name='Код купона')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(verbose_name='описание')),
                ('count', models.CharField(verbose_name='Сумма начисления/списания')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='Bonuses.coin', verbose_name='Мяукоины пользователя')),
            ],
            options={
                'verbose_name': 'История',
                'db_table': 'History',
            },
        ),
    ]
