# Generated by Django 4.2.16 on 2024-10-28 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male')], default='FEMALE', max_length=6)),
                ('description', models.TextField(max_length=500)),
                ('breed', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cats_images', verbose_name='Фотография котика')),
            ],
        ),
    ]
