# Generated by Django 4.2.16 on 2025-02-28 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Кличка')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('FEMALE', 'кошечка'), ('MALE', 'кот')], default='FEMALE', max_length=7, verbose_name='Пол')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('breed', models.CharField(blank=True, null=True, verbose_name='Порода')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cats_images', verbose_name='Фотография котика')),
            ],
            options={
                'verbose_name': 'Котик',
                'verbose_name_plural': 'Котики',
                'db_table': 'Cats',
            },
        ),
        migrations.CreateModel(
            name='FormForAdopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('phone', models.CharField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адресс эл. почты')),
                ('social', models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сети')),
                ('why_this_cat', models.TextField(verbose_name='Причины взять котика')),
                ('children', models.BooleanField(default=False, verbose_name='Есть дети?')),
                ('has_pet', models.BooleanField(default=False, verbose_name='Есть другие животные?')),
                ('pets', models.TextField(blank=True, null=True, verbose_name='Какие питомцы еще есть')),
            ],
            options={
                'verbose_name': " Анкета 'Взять в семью'",
                'verbose_name_plural': " Анкета 'Взять в семью'",
                'db_table': 'Adopt',
            },
        ),
        migrations.CreateModel(
            name='FormForGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('phone', models.CharField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адресс эл. почты')),
                ('social', models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сети')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('character', models.TextField(verbose_name='Характер коткика')),
                ('features', models.TextField(verbose_name='Особенности котика')),
                ('gender', models.CharField(choices=[('FEMALE', 'кошечка'), ('MALE', 'кот')], default='FEMALE', max_length=7, verbose_name='Пол')),
                ('type_of_help', models.CharField(choices=[('CURATOR', 'Я куратор, хочу с вами сотрудничать'), ('HELPER', 'Я хочу разово помочь одному животному')], default='HELPER', max_length=37, verbose_name='Тип помощи')),
                ('reason', models.TextField(verbose_name='Причина передачить котика')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='give_cats', verbose_name='Фотография котика')),
            ],
            options={
                'verbose_name': " Анкета 'Передать кота в кафе'",
                'verbose_name_plural': " Анкета 'Передать кота в кафе'",
                'db_table': 'Given',
            },
        ),
        migrations.CreateModel(
            name='FormForGuardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания заказа')),
                ('phone', models.CharField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адресс эл. почты')),
                ('social', models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сети')),
                ('amount_of_money', models.CharField(choices=[('400', '400'), ('800', '800'), ('1000', '1000'), ('1500', '1500')], default='400', max_length=4, verbose_name='Сумма на опекунство')),
                ('interval', models.CharField(choices=[('month', 'Месяц'), ('year', 'Год')], default='month', max_length=11, verbose_name='Интервал')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('payment_method', models.CharField(blank=True, null=True)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.productstripe', verbose_name='Имя котика')),
                ('pay_session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.checkoutsessionstripe')),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Payment.pricestripe', verbose_name='План подписки')),
            ],
            options={
                'verbose_name': " Анкета 'Оформить опекунство'",
                'verbose_name_plural': " Анкета 'Оформить опекунство'",
                'db_table': 'Guardianship',
            },
        ),
    ]
