# Generated by Django 4.2.16 on 2024-10-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'verbose_name': 'Котик', 'verbose_name_plural': 'Котики'},
        ),
        migrations.AlterModelTable(
            name='cats',
            table='Cats',
        ),
    ]
