# Generated by Django 4.2.16 on 2025-03-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formforguardianship',
            name='use_bonuses',
            field=models.BooleanField(default=False, verbose_name='Использовались ли бонусы во время оплаты'),
        ),
    ]
