# Generated by Django 4.2.16 on 2024-10-29 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0002_alter_cats_options_alter_cats_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='breed',
            field=models.CharField(blank=True, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'кошечка'), ('MALE', 'кот')], default='FEMALE', max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Кличка'),
        ),
    ]
