# Generated by Django 4.2.16 on 2024-11-03 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0003_alter_cats_birthday_alter_cats_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCs', models.TextField(verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Адресс эл. почты')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('social', models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сети')),
            ],
            options={
                'db_table': 'MainInformation',
            },
        ),
        migrations.CreateModel(
            name='FormForGuardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_money', models.DecimalField(decimal_places=2, default=400.0, max_digits=5, verbose_name='Сумма на опекунства')),
                ('cat_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Cats.cats', verbose_name='Имя котика')),
                ('inf_about_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.maininfform')),
            ],
            options={
                'verbose_name': " Анкета 'Оформить опекунство семью'",
                'verbose_name_plural': " Анкета 'Оформить опекунство семью'",
                'db_table': 'Guardianship',
            },
        ),
        migrations.CreateModel(
            name='FormForGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('character', models.TextField(verbose_name='Характер коткика')),
                ('features', models.TextField(verbose_name='Особенности котика')),
                ('gender', models.CharField(choices=[('FEMALE', 'кошечка'), ('MALE', 'кот')], default='FEMALE', max_length=7, verbose_name='Пол')),
                ('type_of_help', models.CharField(choices=[('CURATOR', 'Я куратор, хочу с вами сотрудничать'), ('HELPER', 'Я хочу разово помочь одному животному')], default='HELPER', max_length=37, verbose_name='Тип помощи')),
                ('reason', models.TextField(verbose_name='Причина передачить котика')),
                ('image', models.ImageField(blank=True, null=True, upload_to='give_cats', verbose_name='Фотография котика')),
                ('inf_about_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.maininfform')),
            ],
            options={
                'verbose_name': " Анкета 'Передать кота в кафе'",
                'verbose_name_plural': " Анкета 'Передать кота в кафе'",
                'db_table': 'Given',
            },
        ),
        migrations.CreateModel(
            name='FormForAdopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_this_cat', models.TextField(verbose_name='Причины взять котика')),
                ('children', models.BooleanField(default=False, verbose_name='Есть ли дети?')),
                ('has_pets', models.BooleanField(default=False, verbose_name='Есть ли другие животные?')),
                ('pets', models.TextField(blank=True, null=True)),
                ('cat_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Cats.cats', verbose_name='Имя котика')),
                ('inf_about_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.maininfform')),
            ],
            options={
                'verbose_name': " Анкета 'Взять в семью'",
                'verbose_name_plural': " Анкета 'Взять в семью'",
                'db_table': 'Adopt',
            },
        ),
    ]
