# Generated by Django 4.2.16 on 2025-03-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0003_formforguardianship_use_bonuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formforguardianship',
            name='use_bonuses',
        ),
    ]
