# Generated by Django 4.2.16 on 2025-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0004_remove_formforguardianship_use_bonuses'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formforguardianship',
            index=models.Index(condition=models.Q(('session_key__isnull', False)), fields=['session_key'], name='guardian_session_key_not_null'),
        ),
    ]
