# Generated by Django 4.2.16 on 2024-11-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0004_maininfform_formforguardianship_formforgive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfform',
            name='comment',
        ),
    ]
