# Generated by Django 4.2.16 on 2024-11-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0005_remove_maininfform_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formforadopt',
            old_name='has_pets',
            new_name='hasPets',
        ),
    ]
