# Generated by Django 4.2.16 on 2024-11-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0006_rename_has_pets_formforadopt_haspets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formforadopt',
            old_name='hasPets',
            new_name='has_pets',
        ),
    ]
