# Generated by Django 4.2.16 on 2024-11-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0007_rename_haspets_formforadopt_has_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formforadopt',
            old_name='has_pets',
            new_name='has_pet',
        ),
    ]
