# Generated by Django 4.2.16 on 2024-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0008_rename_has_pets_formforadopt_has_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formforadopt',
            name='inf_about_person',
        ),
        migrations.RemoveField(
            model_name='formforgive',
            name='inf_about_person',
        ),
        migrations.RemoveField(
            model_name='formforguardianship',
            name='inf_about_person',
        ),
        migrations.AddField(
            model_name='formforadopt',
            name='FCs',
            field=models.TextField(default=None, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='formforadopt',
            name='email',
            field=models.CharField(default=None, max_length=254, unique=True, verbose_name='Адресс эл. почты'),
        ),
        migrations.AddField(
            model_name='formforadopt',
            name='phone',
            field=models.CharField(default=None, max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='formforadopt',
            name='social',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сети'),
        ),
        migrations.AddField(
            model_name='formforgive',
            name='FCs',
            field=models.TextField(default=None, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='formforgive',
            name='email',
            field=models.CharField(default=None, max_length=254, unique=True, verbose_name='Адресс эл. почты'),
        ),
        migrations.AddField(
            model_name='formforgive',
            name='phone',
            field=models.CharField(default=None, max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='formforgive',
            name='social',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сети'),
        ),
        migrations.AddField(
            model_name='formforguardianship',
            name='FCs',
            field=models.TextField(default=None, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='formforguardianship',
            name='email',
            field=models.CharField(default=None, max_length=254, unique=True, verbose_name='Адресс эл. почты'),
        ),
        migrations.AddField(
            model_name='formforguardianship',
            name='phone',
            field=models.CharField(default=None, max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='formforguardianship',
            name='social',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сети'),
        ),
        migrations.DeleteModel(
            name='MainInfForm',
        ),
    ]
