# Generated by Django 4.2.16 on 2024-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0009_remove_formforadopt_inf_about_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforgive',
            name='FCs',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='formforgive',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforgive',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
