# Generated by Django 4.2.16 on 2024-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0011_alter_formforadopt_fcs_alter_formforadopt_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formforadopt',
            name='FCs',
        ),
        migrations.RemoveField(
            model_name='formforgive',
            name='FCs',
        ),
        migrations.RemoveField(
            model_name='formforguardianship',
            name='FCs',
        ),
        migrations.AddField(
            model_name='formforadopt',
            name='Name',
            field=models.CharField(default=None, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='formforgive',
            name='Name',
            field=models.CharField(default=None, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='formforguardianship',
            name='Name',
            field=models.CharField(default=None, verbose_name='Имя'),
        ),
    ]
