# Generated by Django 4.2.16 on 2024-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0012_remove_formforadopt_fcs_remove_formforgive_fcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforadopt',
            name='Name',
            field=models.CharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='formforgive',
            name='Name',
            field=models.CharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='formforguardianship',
            name='Name',
            field=models.CharField(verbose_name='Имя'),
        ),
    ]
