# Generated by Django 4.2.16 on 2024-11-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0013_alter_formforadopt_name_alter_formforgive_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforadopt',
            name='Name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='cat_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Cats.cats', verbose_name='Имя котика'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='children',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Есть ли дети?'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='has_pet',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Есть ли другие животные?'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='why_this_cat',
            field=models.TextField(blank=True, null=True, verbose_name='Причины взять котика'),
        ),
        migrations.AlterField(
            model_name='formforgive',
            name='reason',
            field=models.TextField(verbose_name='Причина пе, blank=True, null=True,редачить котика'),
        ),
    ]
