# Generated by Django 4.2.16 on 2024-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0015_alter_formforadopt_name_alter_formforadopt_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforadopt',
            name='Name',
            field=models.CharField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='children',
            field=models.BooleanField(default=False, verbose_name='Есть дети?'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='has_pet',
            field=models.BooleanField(default=False, verbose_name='Есть другие животные?'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='why_this_cat',
            field=models.TextField(verbose_name='Причины взять котика'),
        ),
    ]
