# Generated by Django 4.2.16 on 2024-11-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0016_alter_formforadopt_name_alter_formforadopt_children_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formforadopt',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='formforgive',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='formforguardianship',
            old_name='Name',
            new_name='name',
        ),
    ]
