# Generated by Django 4.2.16 on 2024-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0017_rename_name_formforadopt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforadopt',
            name='pets',
            field=models.TextField(blank=True, null=True, verbose_name='Какие питомцы еще есть'),
        ),
    ]
