# Generated by Django 4.2.16 on 2024-11-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0018_alter_formforadopt_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforadopt',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='formforgive',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforgive',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='formforguardianship',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforguardianship',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
