# Generated by Django 4.2.16 on 2024-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0019_alter_formforadopt_email_alter_formforadopt_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforadopt',
            name='phone',
            field=models.CharField(verbose_name='Номер телефона'),
        ),
    ]
