# Generated by Django 4.2.16 on 2024-11-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0020_alter_formforadopt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforgive',
            name='phone',
            field=models.CharField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='formforguardianship',
            name='phone',
            field=models.CharField(verbose_name='Номер телефона'),
        ),
    ]
