# Generated by Django 4.2.16 on 2024-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0021_alter_formforgive_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforgive',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
