# Generated by Django 4.2.16 on 2024-11-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0022_alter_formforgive_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforguardianship',
            name='amount_of_money',
            field=models.CharField(choices=[('1', '400'), ('2', '800'), ('3', '1000'), ('4', '1500')], default='1', max_length=4, verbose_name='Сумма на опекунства'),
        ),
    ]
