# Generated by Django 4.2.16 on 2024-11-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_username'),
        ('Cats', '0023_alter_formforguardianship_amount_of_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='formforguardianship',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='formforguardianship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
