# Generated by Django 4.2.16 on 2024-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0024_formforguardianship_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforguardianship',
            name='amount_of_money',
            field=models.CharField(choices=[(400, '400'), (800, '800'), (1000, '1000'), (1500, '1500')], default='1', max_length=4, verbose_name='Сумма на опекунства'),
        ),
    ]
