# Generated by Django 4.2.16 on 2024-11-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0025_alter_formforguardianship_amount_of_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforguardianship',
            name='amount_of_money',
            field=models.CharField(choices=[(400, '400'), (800, '800'), (1000, '1000'), (1500, '1500')], default=400, max_length=4, verbose_name='Сумма на опекунства'),
        ),
    ]
