# Generated by Django 4.2.16 on 2024-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0027_alter_formforguardianship_amount_of_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='formforguardianship',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
