# Generated by Django 4.2.16 on 2024-11-14 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cats', '0028_formforguardianship_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforguardianship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
