# Generated by Django 4.2.16 on 2024-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0029_alter_formforguardianship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforgive',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='give_cats', verbose_name='Фотография котика'),
        ),
    ]
