# Generated by Django 4.2.16 on 2024-11-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0030_alter_formforgive_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formforguardianship',
            name='user',
        ),
        migrations.AlterField(
            model_name='formforadopt',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforgive',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адресс эл. почты'),
        ),
        migrations.AlterField(
            model_name='formforguardianship',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адресс эл. почты'),
        ),
    ]
