# Generated by Django 4.2.16 on 2024-11-20 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cats', '0031_remove_formforguardianship_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formforguardianship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
