# Generated by Django 4.2.16 on 2024-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0032_formforguardianship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforguardianship',
            name='user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
